using System;

namespace RestaurantPOS.Core.Entities
{
    /// <summary>
    /// Represents a report generated by the system.  This entity stores the type of the report
    /// and any associated data in serialized form.  The actual generation logic belongs in
    /// the application layer.
    /// </summary>
    public class Report
    {
        public int Id { get; set; }
        public ReportType Type { get; set; }
        public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
        public string? Data { get; set; }
    }

    /// <summary>
    /// Enumerates the types of reports supported by the system.
    /// </summary>
    public enum ReportType
    {
        SalesSummary,
        ProductSales,
        VoidSummary,
        TimeClock,
        TrendHourly,
        SystemLog
    }
}